/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SportShoesHouse;

import javax.swing.JOptionPane;

/**
 *
 * @author eyya
 */
public class AdminHomepage extends javax.swing.JFrame {

    
    String username;
    /**
     * Creates new form AdminOptionReg
     */
    public AdminHomepage() {
        initComponents();
    }
    
    public AdminHomepage(String User) 
    {
        username = User;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBtnReport = new javax.swing.JPanel();
        jLabelReport = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jBtnProdDet = new javax.swing.JPanel();
        jLabelProduct = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jBtnEmpMenu = new javax.swing.JPanel();
        jLabelEmpMenu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jBtnAdminProf = new javax.swing.JPanel();
        jLabelAdminProfile = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelAdminName = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Portal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 255, 204));
        jPanel4.setToolTipText("SSHIMS");
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(253, 253, 253));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 198, 198));
        jLabel1.setText("Logout");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel5.setText("Authentic Shoes Inventory Management System");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 34, 830, 52));

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 35)); // NOI18N
        jLabel4.setText("Admin Portal");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 35)); // NOI18N
        jLabel7.setText("Welcome");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel8.setText("to");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 360));

        jBtnReport.setBackground(new java.awt.Color(249, 249, 249));
        jBtnReport.setToolTipText("Product Report");
        jBtnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnReportMouseClicked(evt);
            }
        });
        jBtnReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Accounting_100px.png"))); // NOI18N
        jLabelReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReportMouseClicked(evt);
            }
        });
        jBtnReport.add(jLabelReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 140, 100));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel13.setText("Report");
        jBtnReport.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 120, 60));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Staff_100px.png"))); // NOI18N
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 90));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(73, 196, 220));
        jLabel15.setText("Employee Details");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 50));

        jBtnReport.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 170, 140));

        jPanel2.add(jBtnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 190, 170));

        jBtnProdDet.setBackground(new java.awt.Color(249, 249, 249));
        jBtnProdDet.setToolTipText("Product Information");
        jBtnProdDet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnProdDetMouseClicked(evt);
            }
        });
        jBtnProdDet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Trainers_100px_1.png"))); // NOI18N
        jLabelProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProductMouseClicked(evt);
            }
        });
        jBtnProdDet.add(jLabelProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 140, 90));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel11.setText("Product Menu");
        jBtnProdDet.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 150, 60));

        jPanel2.add(jBtnProdDet, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 190, 170));

        jBtnEmpMenu.setBackground(new java.awt.Color(249, 249, 249));
        jBtnEmpMenu.setToolTipText("Employee Information");
        jBtnEmpMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEmpMenuMouseClicked(evt);
            }
        });
        jBtnEmpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Staff_100px.png"))); // NOI18N
        jLabelEmpMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEmpMenuMouseClicked(evt);
            }
        });
        jBtnEmpMenu.add(jLabelEmpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 140, 90));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel9.setText("Staff Menu");
        jBtnEmpMenu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 130, 60));

        jPanel2.add(jBtnEmpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 190, 150));

        jBtnAdminProf.setBackground(new java.awt.Color(249, 249, 249));
        jBtnAdminProf.setToolTipText("Edit Admin Profile");
        jBtnAdminProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAdminProfMouseClicked(evt);
            }
        });
        jBtnAdminProf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAdminProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Name_100px.png"))); // NOI18N
        jLabelAdminProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAdminProfileMouseClicked(evt);
            }
        });
        jBtnAdminProf.add(jLabelAdminProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 90));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel6.setText("Admin Profile");
        jBtnAdminProf.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 150, 60));

        jPanel2.add(jBtnAdminProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 190, 170));

        jLabelAdminName.setText("Name admin login");
        jPanel2.add(jLabelAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 90, 120, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_User_20px_3.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(794, 552));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAdminProfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAdminProfMouseClicked
        // TODO add your handling code here:
        AdminChangePwd a = new AdminChangePwd();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnAdminProfMouseClicked

    private void jLabelAdminProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdminProfileMouseClicked
        // TODO add your handling code here:
        AdminChangePwd a = new AdminChangePwd();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelAdminProfileMouseClicked

    private void jLabelEmpMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmpMenuMouseClicked
        // TODO add your handling code here:
        AdminStaffMenu e = new AdminStaffMenu();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelEmpMenuMouseClicked

    private void jLabelReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReportMouseClicked
        // TODO add your handling code here:
        Report r = new Report();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelReportMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
         { 
            String ObjButtons[] = {"Yes","No"};
            int PromptResult = JOptionPane.showOptionDialog(null,"Are you sure you want to logout?","Sport Shoes House",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE,null,ObjButtons,ObjButtons[1]);
            if(PromptResult==JOptionPane.YES_OPTION)
            {
                JOptionPane.showMessageDialog(null, "User Log Out");
                new LoginAdmin().setVisible(true);
            }
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jBtnEmpMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEmpMenuMouseClicked
        // TODO add your handling code here:
        AdminStaffMenu e = new AdminStaffMenu(username);
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnEmpMenuMouseClicked

    private void jBtnReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnReportMouseClicked
        // TODO add your handling code here:
        Report r = new Report();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnReportMouseClicked

    private void jBtnProdDetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnProdDetMouseClicked
        // TODO add your handling code here:
        ProductMenu p = new ProductMenu(username);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnProdDetMouseClicked

    private void jLabelProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProductMouseClicked
        // TODO add your handling code here:
        ProductMenu p = new ProductMenu();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelProductMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jLabelAdminName.setText(username);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtnAdminProf;
    private javax.swing.JPanel jBtnEmpMenu;
    private javax.swing.JPanel jBtnProdDet;
    private javax.swing.JPanel jBtnReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAdminName;
    private javax.swing.JLabel jLabelAdminProfile;
    private javax.swing.JLabel jLabelEmpMenu;
    private javax.swing.JLabel jLabelProduct;
    private javax.swing.JLabel jLabelReport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
