/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SportShoesHouse;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author eyya
 */
public class Ordering extends javax.swing.JFrame {

    /**
     * Creates new form Ordering
     */
    public Ordering() {
        initComponents();
    }
    
    String[] items = new String[50];
    
    double[] cost = new double[50];
    
    double[] quantity = new double[50];
    
    double[] price2 = new double[50];
    
    int x=0, y=0, z=0;
    
    double subtotal=0, tax=0, total=0, price=0;
    
    String paymentConvert="";
    String sizeConvert="";
    
    DecimalFormat df=new DecimalFormat("0.00");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        LblNike1 = new javax.swing.JLabel();
        LblNike2 = new javax.swing.JLabel();
        jLabelNikeName1 = new javax.swing.JLabel();
        jLabelNikeName2 = new javax.swing.JLabel();
        jButtonBuy1 = new javax.swing.JButton();
        jButtonBuy2 = new javax.swing.JButton();
        jLabelNikePrice1 = new javax.swing.JLabel();
        jLabelNikePrice2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        LblAdidas1 = new javax.swing.JLabel();
        LblAdidas2 = new javax.swing.JLabel();
        jLabelAdiasName1 = new javax.swing.JLabel();
        jLabelAdiasName2 = new javax.swing.JLabel();
        jLabelAdidasPrice1 = new javax.swing.JLabel();
        jLabelAdidasPrice2 = new javax.swing.JLabel();
        jButtonBuy3 = new javax.swing.JButton();
        jButtonBuy4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        LblAsics1 = new javax.swing.JLabel();
        LblAsics2 = new javax.swing.JLabel();
        jLabelAsicsName1 = new javax.swing.JLabel();
        jLabelAsicsName2 = new javax.swing.JLabel();
        jLabelAsicsPrice1 = new javax.swing.JLabel();
        jButtonBuy6 = new javax.swing.JButton();
        jButtonBuy5 = new javax.swing.JButton();
        jLabelAsicsPrice2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelSize = new javax.swing.JLabel();
        jComboBoxSize = new javax.swing.JComboBox<>();
        jLabelItem = new javax.swing.JLabel();
        jButtonCalTotal = new javax.swing.JButton();
        jLabelSubTot = new javax.swing.JLabel();
        jLabelGST = new javax.swing.JLabel();
        jLabelGST1 = new javax.swing.JLabel();
        jButtonAddItem = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jLabelQty = new javax.swing.JLabel();
        jTextFieldQty = new javax.swing.JTextField();
        jLabelPrice = new javax.swing.JLabel();
        jLabelSize1 = new javax.swing.JLabel();
        jRadioButtonCOD = new javax.swing.JRadioButton();
        jRadioButtonOnlineBanking = new javax.swing.JRadioButton();
        jLabelCustName = new javax.swing.JLabel();
        jTextFieldCustName = new javax.swing.JTextField();
        jLabelAddress = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jTextFieldItem = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JLabel();
        jTextFieldSubTotal = new javax.swing.JLabel();
        jTextFieldGst = new javax.swing.JLabel();
        jTextFieldOverallTot = new javax.swing.JLabel();
        jButtonOrderView = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSummary = new javax.swing.JTextArea();
        jButtonBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuHome = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Form");

        jScrollPane2.setWheelScrollingEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1253, 1000));

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel3.setText("AUTHENTIC SHOES INVENTORY MANAGEMENT SYSTEM");
        jLabel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(153, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("CDG x Converse"));

        LblNike1.setBackground(new java.awt.Color(255, 255, 255));
        LblNike1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cdg2.jpg"))); // NOI18N

        LblNike2.setBackground(new java.awt.Color(255, 255, 255));
        LblNike2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cdg1.jpg"))); // NOI18N

        jLabelNikeName1.setText("CDGxConverse lowcut");

        jLabelNikeName2.setText("CDGxConverse highcut");

        jButtonBuy1.setText("Buy");
        jButtonBuy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuy1ActionPerformed(evt);
            }
        });

        jButtonBuy2.setText("Buy");
        jButtonBuy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuy2ActionPerformed(evt);
            }
        });

        jLabelNikePrice1.setText("RM520.00");

        jLabelNikePrice2.setText("RM695.00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelNikePrice1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNikeName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButtonBuy1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNikePrice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNikeName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBuy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblNike1)
                        .addGap(18, 18, 18)
                        .addComponent(LblNike2)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblNike2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblNike1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNikeName1)
                    .addComponent(jLabelNikeName2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNikePrice1)
                    .addComponent(jLabelNikePrice2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuy1)
                    .addComponent(jButtonBuy2))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(153, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Adidas Shoes"));

        LblAdidas1.setBackground(new java.awt.Color(255, 255, 255));
        LblAdidas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/falcon.jpg"))); // NOI18N

        LblAdidas2.setBackground(new java.awt.Color(255, 255, 255));
        LblAdidas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yeezy2.jpg"))); // NOI18N

        jLabelAdiasName1.setText("Adidas Falcon");

        jLabelAdiasName2.setText("Adidas Yeezy Boost 350");

        jLabelAdidasPrice1.setText("RM400.00");

        jLabelAdidasPrice2.setText("RM3500.00");

        jButtonBuy3.setText("Buy");
        jButtonBuy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuy3ActionPerformed(evt);
            }
        });

        jButtonBuy4.setText("Buy");
        jButtonBuy4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuy4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelAdidasPrice1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAdiasName1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                            .addComponent(jButtonBuy3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAdidasPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAdiasName2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuy4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(LblAdidas1)
                        .addGap(18, 18, 18)
                        .addComponent(LblAdidas2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblAdidas2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAdidas1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdiasName1)
                    .addComponent(jLabelAdiasName2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdidasPrice2)
                    .addComponent(jLabelAdidasPrice1))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuy3)
                    .addComponent(jButtonBuy4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(153, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Balenciaga Shoes"));

        LblAsics1.setBackground(new java.awt.Color(255, 255, 255));
        LblAsics1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/balen1.jpg"))); // NOI18N

        LblAsics2.setBackground(new java.awt.Color(255, 255, 255));
        LblAsics2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/balen2.jpg"))); // NOI18N

        jLabelAsicsName1.setText("Balenciaga Tennis Vintage");

        jLabelAsicsName2.setText("Balenciaga Speed Knitted");

        jLabelAsicsPrice1.setText("RM5500.00");

        jButtonBuy6.setText("Buy");
        jButtonBuy6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuy6ActionPerformed(evt);
            }
        });

        jButtonBuy5.setText("Buy");
        jButtonBuy5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuy5ActionPerformed(evt);
            }
        });

        jLabelAsicsPrice2.setText("RM7500.00");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelAsicsName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblAsics1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblAsics2)
                            .addComponent(jLabelAsicsName2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabelAsicsPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelAsicsPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jButtonBuy5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuy6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblAsics2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAsics1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAsicsName1)
                    .addComponent(jLabelAsicsName2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAsicsPrice1)
                    .addComponent(jLabelAsicsPrice2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuy6)
                    .addComponent(jButtonBuy5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 13))); // NOI18N

        jLabelSize.setText("Size :");

        jComboBoxSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabelItem.setText("Item:");

        jButtonCalTotal.setText("Calculate (RM)");
        jButtonCalTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalTotalActionPerformed(evt);
            }
        });

        jLabelSubTot.setText("Sub Total RM :");

        jLabelGST.setText("GST 6% RM :");

        jLabelGST1.setText("Overall Total (RM) :");

        jButtonAddItem.setText("Add More Item");
        jButtonAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jLabelQty.setText("Quantity:");

        jLabelPrice.setText("Price:");

        jLabelSize1.setText("Payment:");

        jRadioButtonCOD.setText("Cash-On-Delivery");

        jRadioButtonOnlineBanking.setText("Online Banking");

        jLabelCustName.setText("Customer Name:");

        jLabelAddress.setText("Address:");

        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jScrollPane3.setViewportView(jTextAreaAddress);

        jTextFieldItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldItem.setEnabled(false);

        jTextFieldPrice.setEnabled(false);

        jTextFieldSubTotal.setEnabled(false);

        jTextFieldGst.setEnabled(false);

        jTextFieldOverallTot.setEnabled(false);

        jButtonOrderView.setText("Order View");
        jButtonOrderView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButtonAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCalTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelSubTot)
                                    .addComponent(jLabelPrice)
                                    .addComponent(jLabelGST)
                                    .addComponent(jLabelGST1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldGst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldOverallTot, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonOrderView, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelSize1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 27, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelCustName)
                                    .addComponent(jLabelItem)
                                    .addComponent(jLabelQty)
                                    .addComponent(jLabelSize)
                                    .addComponent(jLabelAddress))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldQty, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButtonCOD)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonOnlineBanking))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(jTextFieldCustName)
                            .addComponent(jTextFieldItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCustName)
                    .addComponent(jTextFieldCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSize1)
                    .addComponent(jRadioButtonCOD)
                    .addComponent(jRadioButtonOnlineBanking))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSize)
                    .addComponent(jComboBoxSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelItem)
                    .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQty)
                    .addComponent(jTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddItem)
                    .addComponent(jButtonCalTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPrice)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSubTot)
                    .addComponent(jTextFieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGST)
                    .addComponent(jTextFieldGst, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGST1)
                    .addComponent(jTextFieldOverallTot, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOrderView)
                    .addComponent(jButtonReset))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(153, 255, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Purchase Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 13))); // NOI18N

        jTextAreaSummary.setColumns(20);
        jTextAreaSummary.setRows(5);
        jTextAreaSummary.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaSummary);

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jButtonBack)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButtonBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setText("Ordering Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        jMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        jMenuHome.setText("Home");
        jMenuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHomeActionPerformed(evt);
            }
        });
        jMenuBar.add(jMenuHome);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1117, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1135, 978));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHomeActionPerformed
        // TODO add your handling code here:
        new MainPage().setVisible(true);
    }//GEN-LAST:event_jMenuHomeActionPerformed

    private void jButtonBuy5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuy5ActionPerformed
        // TODO add your handling code here:
        jTextFieldItem.setText(("Asics GT 2000"));
        items[x] = "Asics GT 2000         : RM1000.00";
        cost[x]=1000;
    }//GEN-LAST:event_jButtonBuy5ActionPerformed

    private void jButtonBuy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuy1ActionPerformed
        // TODO add your handling code here:
        jTextFieldItem.setText(("CDGxConverse lowcut"));
        items[x] = "CDGxConverse lowcut : RM520.";
	cost[x]=600;
    }//GEN-LAST:event_jButtonBuy1ActionPerformed

    private void jButtonBuy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuy2ActionPerformed
        // TODO add your handling code here:
        jTextFieldItem.setText(("Nike Air Uptempo"));
        items[x] = "Nike Air Uptempo      : RM800.00";
        cost[x]=800;
    }//GEN-LAST:event_jButtonBuy2ActionPerformed

    private void jButtonBuy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuy3ActionPerformed
        // TODO add your handling code here:
        jTextFieldItem.setText(("Adidas ZX Flux"));
        items[x] = "Adidas ZX Flux        : RM400.00";
        cost[x]=400;
    }//GEN-LAST:event_jButtonBuy3ActionPerformed

    private void jButtonBuy4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuy4ActionPerformed
        // TODO add your handling code here:
        jTextFieldItem.setText(("Adidas Yeezy Boost"));
        items[x] = "Adidas Yeezy Boost    : RM800.00";
        cost[x]=800;
    }//GEN-LAST:event_jButtonBuy4ActionPerformed

    private void jButtonBuy6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuy6ActionPerformed
        // TODO add your handling code here:
        jTextFieldItem.setText(("Asics Gel Nimbus"));
        items[x] = "Asics Gel Nimbus      : RM699.99";
        cost[x]=699.99;
    }//GEN-LAST:event_jButtonBuy6ActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextFieldItem.setText("");
	x=0;y=0;z=0;
        jTextFieldCustName.setText(null);
        jTextAreaAddress.setText(null);
	jComboBoxSize.setSelectedIndex(0);
	jTextFieldQty.setText(null);
	jTextFieldPrice.setText(null);
	jTextFieldSubTotal.setText(null);
	jTextFieldGst.setText(null);
	jTextFieldOverallTot.setText(null);
	jTextAreaSummary.setText(null);
	subtotal=0;
	tax=0;
	total=0;
	price=0;
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemActionPerformed
        // TODO add your handling code here:
        jComboBoxSize.setSelectedIndex(0);
        jTextFieldQty.setText("");
        jTextFieldPrice.setText("");
        jTextFieldItem.setText("");
    }//GEN-LAST:event_jButtonAddItemActionPerformed

    private void jButtonCalTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalTotalActionPerformed
        // TODO add your handling code here:
        if(jTextFieldItem.getText().equalsIgnoreCase(""))
        {	
            jTextFieldItem.requestFocus();
            jTextFieldCustName.setText(null);
            jTextAreaAddress.setText(null);
            jTextFieldPrice.setText(null);
            jTextFieldSubTotal.setText(null);
            jTextFieldGst.setText(null);
            jTextFieldOverallTot.setText(null);
            jTextAreaSummary.setText(null);
            subtotal=0;
            tax=0;
            total=0;
            price=0;
            JOptionPane.showMessageDialog(null,"Error, Please Enter Item First");//edit
        }
        else
        {
            calculateprice();
            while(z<x)
            {
                subtotal = subtotal + price2[z];
                z++;
            }
            tax = subtotal * 0.06;
            total = subtotal + tax;
                    
            jTextFieldSubTotal.setText(String.valueOf(df.format(subtotal)));
            jTextFieldGst.setText(String.valueOf(df.format(tax)));
            jTextFieldOverallTot.setText(String.valueOf(df.format(total)));	
        }		
    }//GEN-LAST:event_jButtonCalTotalActionPerformed

    private void jButtonOrderViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderViewActionPerformed
        // TODO add your handling code here:
        ViewOrder v = new ViewOrder();
            
        ViewOrder.jLabelCustName.setText(this.jTextFieldCustName.getText());
        ViewOrder.jTextAreaAddress.setText(this.jTextAreaAddress.getText());
        ViewOrder.jLabelSummary.setText(this.jTextAreaSummary.getText());
        ViewOrder.jLabelSubTotal.setText(this.jTextFieldSubTotal.getText());
        jLabelGST.setText(this.jTextFieldGst.getText());   
        ViewOrder.jLabelOvrTotal.setText(this.jTextFieldOverallTot.getText());
        v.setVisible(true); 
    }//GEN-LAST:event_jButtonOrderViewActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        dispose();
        new StaffHomepage().setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    //Method to calculate price
    public double calculate(double payment)
    {
	quantity[x] = Double.parseDouble((String)jTextFieldQty.getText());  
	double price = (quantity[x]*cost[x])+payment;
	return price;
    }
    
    //Method to display item in purchase order form
    public void calculateprice()
    {
	double payment = 0;

	if(jRadioButtonCOD.isSelected())
	{
            payment=5;
	}
	else if(jRadioButtonOnlineBanking.isSelected())
	{
            payment=7.9;
	}
	
        price = calculate(payment);
	price2[x] = price;
	jTextFieldPrice.setText(String.valueOf(price));
				
	if(payment==5)
        {
            paymentConvert="Cash-On-Delivery : RM5.00 ";
	}	
	else if(payment==7.9)
	{
            paymentConvert="Online Banking :RM7.90";
	}	  		
	else
        {
						
	}

        x++;
			
	while(y<x)
	{
            jTextAreaSummary.append("\n"+String.valueOf(items[y]+"\t  x  "+quantity[y]+"\tSize :"+jComboBoxSize.getSelectedItem()+ 
                    "\t\t Total Price : RM  " + df.format(price2[y]) + "\t"+paymentConvert));
            y++;
	}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordering().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblAdidas1;
    private javax.swing.JLabel LblAdidas2;
    private javax.swing.JLabel LblAsics1;
    private javax.swing.JLabel LblAsics2;
    private javax.swing.JLabel LblNike1;
    private javax.swing.JLabel LblNike2;
    private javax.swing.JButton jButtonAddItem;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBuy1;
    private javax.swing.JButton jButtonBuy2;
    private javax.swing.JButton jButtonBuy3;
    private javax.swing.JButton jButtonBuy4;
    private javax.swing.JButton jButtonBuy5;
    private javax.swing.JButton jButtonBuy6;
    private javax.swing.JButton jButtonCalTotal;
    private javax.swing.JButton jButtonOrderView;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboBoxSize;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelAdiasName1;
    private javax.swing.JLabel jLabelAdiasName2;
    private javax.swing.JLabel jLabelAdidasPrice1;
    private javax.swing.JLabel jLabelAdidasPrice2;
    private javax.swing.JLabel jLabelAsicsName1;
    private javax.swing.JLabel jLabelAsicsName2;
    private javax.swing.JLabel jLabelAsicsPrice1;
    private javax.swing.JLabel jLabelAsicsPrice2;
    private javax.swing.JLabel jLabelCustName;
    private javax.swing.JLabel jLabelGST;
    private javax.swing.JLabel jLabelGST1;
    private javax.swing.JLabel jLabelItem;
    private javax.swing.JLabel jLabelNikeName1;
    private javax.swing.JLabel jLabelNikeName2;
    private javax.swing.JLabel jLabelNikePrice1;
    private javax.swing.JLabel jLabelNikePrice2;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelQty;
    private javax.swing.JLabel jLabelSize;
    private javax.swing.JLabel jLabelSize1;
    private javax.swing.JLabel jLabelSubTot;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuHome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonCOD;
    private javax.swing.JRadioButton jRadioButtonOnlineBanking;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTextArea jTextAreaAddress;
    public static javax.swing.JTextArea jTextAreaSummary;
    public static javax.swing.JTextField jTextFieldCustName;
    public static javax.swing.JLabel jTextFieldGst;
    private javax.swing.JLabel jTextFieldItem;
    public static javax.swing.JLabel jTextFieldOverallTot;
    private javax.swing.JLabel jTextFieldPrice;
    private javax.swing.JTextField jTextFieldQty;
    public static javax.swing.JLabel jTextFieldSubTotal;
    // End of variables declaration//GEN-END:variables
}
